# Generated by Django 4.0.2 on 2022-07-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoriy',
            new_name='category',
        ),
    ]
